const bookshelf = [
    {
        "id": "3-XZAAAACAAJ",
        "title": "いま平和とは",
        "author": "最上敏樹",
        "published_at": "2006-03",
        "isbn": "9784004310006",
        "thumbnail": "http://books.google.com/books/content?id=3-XZAAAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
        "description": "二一世紀に入っても武力紛争や大規模な人権侵害は止むことがなく、暴力と憎悪の連鎖が続いている。そして世界には、新たな分断線が引かれ始めた。いま、平和を築き上げるために、国連や国際法そして市民には何ができるのだろうか。いかにすれば、人間は対立を超えて真に和解できるのか。人権と人道の時代を迎えるための条件をさぐる9話。",
        "publisher": "岩波書店",
        "pages": 100,
        "memo": "メモ",
        "status": "読み終わった",
        "created_at": "2025-04-10",
        "finished_at": "2025-04-13",
    },
    {
        "id": "1lQnAQAAIAAJ",
        "title": "世界共和国へ",
        "author": "柄谷行人",
        "published_at": "2006-04",
        "isbn": "9784004310013",
        "thumbnail": "http://books.google.com/books/content?id=1lQnAQAAIAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
        "description": "「資本=ネーション=国家」という接合体に覆われた現在の世界からは、それを超えるための理念も想像力も失われてしまった。資本制とネーションと国家の起源をそれぞれ三つの基礎的な交換様式から解明し、その接合体から抜け出す方法を「世界共和国」への道すじの中に探ってゆく。二一世紀の世界を変える大胆な社会構想。",
        "publisher": "岩波書店",
        "pages": 100,
        "memo": "メモ",
        "status": "読み終わった",
        "created_at": "2025-04-10",
        "finished_at": "2025-04-13",
    },
    {
        "id": "5V0gAgAACAAJ",
        "title": "憲法とは何か",
        "author": "長谷部恭男",
        "published_at": "2006-04",
        "isbn": "9784004310020",
        "thumbnail": "http://books.google.com/books/content?id=5V0gAgAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
        "description": "憲法は何のためにあるのか。立憲主義とはどういう考えなのか。憲法はわれわれに明るい未来を保障するどころか、ときに人々の生活や生命をも左右する「危険」な存在になりうる。改憲論議が高まりつつある現在、憲法にまつわる様々な誤解や幻想を指摘しながら、その本質についての冷静な考察をうながす「憲法再入門」。",
        "publisher": "岩波書店",
        "pages": 100,
        "memo": "メモ",
        "status": "読み終わった",
        "created_at": "2025-04-10",
        "finished_at": "2025-04-13",
    },
    {
        "id": "T78EAQAAIAAJ",
        "title": "日本宗教史",
        "author": "末木文美士",
        "published_at": "2006-04",
        "isbn": "9784004310037",
        "thumbnail": "http://books.google.com/books/content?id=T78EAQAAIAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
        "description": "『記・紀』にみる神々の記述には仏教が影を落とし、中世には神仏習合から独特な神話が生まれる。近世におけるキリスト教との出会い、国家と個の葛藤する近代を経て、現代新宗教の出現に至るまでを、精神の“古層”が形成され、「発見」されるダイナミックな過程としてとらえ、世俗倫理、権力との関係をも視野に入れた、大胆な通史の試み。",
        "publisher": "岩波書店",
        "pages": 100,
        "memo": "メモ",
        "status": "読み終わった",
        "created_at": "2025-04-10",
        "finished_at": "2025-04-13",
    },
]

export default bookshelf;